// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifgwavjfbobvtymfxuud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmZ3dhdmpmYm9idnR5bWZ4dXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTE1NTgsImV4cCI6MjA2NTgyNzU1OH0.MrQXKm4qF_iHpgnKxgcYCD1v5PJwx2OHCeQnni25z34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);